name: "Update Angular Action"
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here!
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          repo-token: $